// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// PingPingParams represents params for ping operation
//
// Request: GET /ping.
type PingPingParams struct {
	// Message is parsed from request query and declared as message.
	Message string
}
