// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	"github.com/gemyago/apigen/examples/go-apigen-server/pkg/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewErrorValidator() FieldValidator[*models.Error] {
	validateCode := NewSimpleFieldValidator[*interface{}](
		SkipNullValidator(EnsureNonDefault[interface{}]),
	)
	validateMessage := NewSimpleFieldValidator[string](
	)
	
	return func(bindingCtx *BindingContext, value *models.Error) {
		validateCode(bindingCtx.Fork("code"), value.Code)
		validateMessage(bindingCtx.Fork("message"), value.Message)
	}
}
