// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	"github.com/gemyago/apigen/examples/go-apigen-server/pkg/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewErrorValidator(params ModelValidatorParams) FieldValidator[*models.Error] {
	validateCode := NewSimpleFieldValidator[*interface{}](
		SimpleFieldValidatorParams{Field: "code", Location: params.Location},
		SkipNullValidator(EnsureNonDefault[interface{}]),
	)
	validateMessage := NewSimpleFieldValidator[string](
		SimpleFieldValidatorParams{Field: "message", Location: params.Location},
	)
	
	return func(bindingCtx *BindingContext, value *models.Error) {
		validateCode(bindingCtx, value.Code)
		validateMessage(bindingCtx, value.Message)
	}
}
