// Code generated by apigen DO NOT EDIT.

package internal

import (
	"github.com/gemyago/apigen/examples/go-apigen-server/pkg/api/http/v1routes/models"
)
func NewPetValidator() FieldValidator[*models.Pet] {
	return func(bindingCtx *BindingContext, field, location string, value *models.Pet) {
	}
}
