// Code generated by apigen DO NOT EDIT.

package internal

import (
	"github.com/gemyago/apigen/examples/go-apigen-server/pkg/api/http/v1routes/models"
)
func NewPetResponseValidator() FieldValidator[*models.PetResponse] {
	return func(bindingCtx *BindingContext, field, location string, value *models.PetResponse) {
	}
}
