// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	"github.com/gemyago/apigen/examples/go-apigen-server/pkg/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewPetResponseValidator() FieldValidator[*models.PetResponse] {
	
	validateData := NewPetValidator()
	
	return func(bindingCtx *BindingContext, field, location string, value *models.PetResponse) {
		validateData(bindingCtx, "data", location, &value.Data)
	}
}
