// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	"github.com/gemyago/apigen/examples/go-apigen-server/pkg/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewPetResponseValidator(params ModelValidatorParams) FieldValidator[*models.PetResponse] {
	validateData := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Field: "data", Location: params.Location, Required: true, Nullable: false},
		NewPetValidator(ModelValidatorParams{Location: params.Location + ".data"}),
	)
	
	return func(bindingCtx *BindingContext, value *models.PetResponse) {
		validateData(bindingCtx, value.Data)
	}
}
