// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	"github.com/gemyago/apigen/examples/go-apigen-server/pkg/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewPetsResponseValidator(params ModelValidatorParams) FieldValidator[*models.PetsResponse] {
	validateData := NewArrayValidator[*models.Pet](
		NewPetValidator(ModelValidatorParams{Location: params.Location + ".Data"}),
	)
	
	return func(bindingCtx *BindingContext, value *models.PetsResponse) {
		validateData(bindingCtx, value.Data)
	}
}
