// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/apigen/examples/petstore-server-app-layer-go/internal/app/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewPetResponseValidator() FieldValidator[*PetResponse] {
	validateData := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: true, Nullable: false},
		NewPetValidator(),
	)
	
	return func(bindingCtx *BindingContext, value *PetResponse) {
		validateData(bindingCtx.Fork("data"), value.Data)
	}
}
