// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/apigen/examples/petstore-server-app-layer-go/internal/app/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewPetValidator() FieldValidator[*Pet] {
	validateID := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateComments := NewSimpleFieldValidator[string](
	)
	
	return func(bindingCtx *BindingContext, value *Pet) {
		validateID(bindingCtx.Fork("id"), value.ID)
		validateName(bindingCtx.Fork("name"), value.Name)
		validateComments(bindingCtx.Fork("comments"), value.Comments)
	}
}
