// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"
	"time"

	"github.com/gemyago/apigen/examples/go-apigen-server/pkg/api/http/v1routes/models"
	"github.com/gemyago/apigen/examples/go-apigen-server/pkg/api/http/v1routes/internal"
)

// Below is to workaround unused imports.
var _ = time.Time{}

type paramsParserPetsCreatePet struct {
	bindPayload requestParamBinder[*http.Request, *models.Pet]
}

func (p *paramsParserPetsCreatePet) parse(router httpRouter, req *http.Request) (*PetsCreatePetRequest, error) {
	bindingCtx := internal.BindingContext{}
	reqParams := &PetsCreatePetRequest{}
	// body params
	p.bindPayload(&bindingCtx, readRequestBodyValue(req), &reqParams.Payload)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserPetsCreatePet(app *HTTPApp) paramsParser[*PetsCreatePetRequest] {
	return &paramsParserPetsCreatePet{
		bindPayload: newRequestParamBinder(binderParams[*http.Request, *models.Pet]{
			field: "payload",
			location: "body",
			required: true,
			parseValue: parseJSONPayload[*models.Pet],
			validateValue: internal.NewPetValidator(),
		}),
	}
}

type paramsParserPetsGetPetById struct {
	bindPetId requestParamBinder[string, int64]
}

func (p *paramsParserPetsGetPetById) parse(router httpRouter, req *http.Request) (*PetsGetPetByIdRequest, error) {
	bindingCtx := internal.BindingContext{}
	reqParams := &PetsGetPetByIdRequest{}
	// path params
	p.bindPetId(&bindingCtx, readPathValue("petId", router, req), &reqParams.PetId)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserPetsGetPetById(app *HTTPApp) paramsParser[*PetsGetPetByIdRequest] {
	return &paramsParserPetsGetPetById{
		bindPetId: newRequestParamBinder(binderParams[string, int64]{
			field: "petId",
			location: "path",
			required: true,
			parseValue: app.knownParsers.int64InPath,
			validateValue: internal.NewSimpleFieldValidator[int64](
				internal.SimpleFieldValidatorOpts{},
			),
		}),
	}
}

type paramsParserPetsListPets struct {
	bindLimit requestParamBinder[[]string, int64]
	bindOffset requestParamBinder[[]string, int64]
}

func (p *paramsParserPetsListPets) parse(router httpRouter, req *http.Request) (*PetsListPetsRequest, error) {
	bindingCtx := internal.BindingContext{}
	reqParams := &PetsListPetsRequest{}
	// query params
	query := req.URL.Query()
	p.bindLimit(&bindingCtx, readQueryValue("limit", query), &reqParams.Limit)
	p.bindOffset(&bindingCtx, readQueryValue("offset", query), &reqParams.Offset)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserPetsListPets(app *HTTPApp) paramsParser[*PetsListPetsRequest] {
	return &paramsParserPetsListPets{
		bindLimit: newRequestParamBinder(binderParams[[]string, int64]{
			field: "limit",
			location: "query",
			required: true,
			parseValue: app.knownParsers.int64InQuery,
			validateValue: internal.NewSimpleFieldValidator[int64](
				internal.SimpleFieldValidatorOpts{},
				internal.NewMinMaxValueValidator[int64](1, false, true),
				internal.NewMinMaxValueValidator[int64](100, false, false),
			),
		}),
		bindOffset: newRequestParamBinder(binderParams[[]string, int64]{
			field: "offset",
			location: "query",
			required: false,
			parseValue: app.knownParsers.int64InQuery,
			validateValue: internal.NewSimpleFieldValidator[int64](
				internal.SimpleFieldValidatorOpts{},
				internal.NewMinMaxValueValidator[int64](1, false, true),
			),
		}),
	}
}
