// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"encoding/json"
	"fmt"
	"time"

	. "github.com/gemyago/apigen/examples/ping-server-go/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// PingPingRequest represents params for ping operation
//
// Request: GET /ping.
type PingPingRequest struct {
	// Message is parsed from request query and declared as message.
	Message string
}

type PingController struct {
	// GET /ping
	//
	// Request type: PingPingRequest,
	//
	// Response type: Ping200Response
	Ping httpHandlerFactory
}

type PingControllerBuilder struct {
	// GET /ping
	//
	// Request type: PingPingRequest,
	//
	// Response type: Ping200Response
	HandlePing actionBuilder[*PingControllerBuilder, *PingPingRequest, *Ping200Response]
}

func (c *PingControllerBuilder) Finalize() *PingController {
	return &PingController{
		Ping: mustInitializeAction("ping", c.HandlePing.httpHandlerFactory),
	}
}

func BuildPingController() *PingControllerBuilder {
	controllerBuilder := &PingControllerBuilder{}

	// GET /ping
	controllerBuilder.HandlePing.controllerBuilder = controllerBuilder
	controllerBuilder.HandlePing.defaultStatusCode = 200
	controllerBuilder.HandlePing.paramsParserFactory = newParamsParserPingPing

	return controllerBuilder
}

func RegisterPingRoutes(controller *PingController, app *HTTPApp) {
	app.router.HandleRoute("GET", "/ping", controller.Ping(app))
}
