// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"
	"time"

	. "github.com/gemyago/apigen/examples/ping-server-go/internal/api/http/v1routes/models"
	. "github.com/gemyago/apigen/examples/ping-server-go/internal/api/http/v1routes/internal"
)

// Below is to workaround unused imports if that happens.
var _ = BindingContext{}
var _ = http.MethodGet
var _ = time.Time{}
type _ func() Ping200Response

type paramsParserPingPing struct {
	bindMessage requestParamBinder[[]string, string]
}

func (p *paramsParserPingPing) parse(router httpRouter, req *http.Request) (*PingPingRequest, error) {
	bindingCtx := BindingContext{}
	reqParams := &PingPingRequest{}
	// query params
	query := req.URL.Query()
	queryParamsCtx := bindingCtx.Fork("query")
	p.bindMessage(queryParamsCtx.Fork("message"), readQueryValue("message", query), &reqParams.Message)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserPingPing(rootHandler *RootHandler) paramsParser[*PingPingRequest] {
	return &paramsParserPingPing{
		bindMessage: newRequestParamBinder(binderParams[[]string, string]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}
