// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"
	"time"

	. "github.com/gemyago/apigen/examples/ping-server-go/internal/api/http/v1routes/models"
	. "github.com/gemyago/apigen/examples/ping-server-go/internal/api/http/v1routes/internal"
)

// Below is to workaround unused imports if that happens.
var _ = BindingContext{}
var _ = http.MethodGet
var _ = time.Time{}
type _ func() Ping200Response

type paramsParserPingPing struct {
	bindMessage requestParamBinder[[]string, string]
}

func (p *paramsParserPingPing) parse(router httpRouter, req *http.Request) (*PingPingParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &PingPingParams{}
	// query params
	query := req.URL.Query()
	queryParamsCtx := bindingCtx.Fork("query")
	p.bindMessage(queryParamsCtx.Fork("message"), readQueryValue("message", query), &reqParams.Message)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserPingPing(rootHandler *RootHandler) paramsParser[*PingPingParams] {
	return &paramsParserPingPing{
		bindMessage: newRequestParamBinder(binderParams[[]string, string]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}

type pingControllerBuilder struct {
	// GET /ping
	//
	// Request type: PingPingParams,
	//
	// Response type: Ping200Response
	Ping genericHandlerBuilder[
		*PingPingParams,
		*Ping200Response,
		handlerActionFunc[*PingPingParams, *Ping200Response],
		httpHandlerActionFunc[*PingPingParams, *Ping200Response],
	]
}

func newPingControllerBuilder(app *RootHandler) *pingControllerBuilder {
	return &pingControllerBuilder{
		// GET /ping
		Ping: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*PingPingParams,
				*Ping200Response,
			](),
			newHTTPHandlerAdapter[
				*PingPingParams,
				*Ping200Response,
			](),
			makeActionBuilderParams[
				*PingPingParams,
				*Ping200Response,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserPingPing(app),
			},
		),
	}
}
