// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"

	. "github.com/gemyago/apigen/examples/ping-server-go/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports if that happens.
type _ func() Ping200Response

type PingController interface {
	// GET /ping
	//
	// Request type: PingPingParams,
	//
	// Response type: Ping200Response
	Ping(HandlerBuilder[
		*PingPingParams,
		*Ping200Response,
	]) http.Handler
}

// RegisterPingRoutes will attach the following routes to the root handler:
// 
// - GET /ping
// 
// Routes will use provided controller to handle requests.
func(rootHandler *RootHandler) RegisterPingRoutes(controller PingController) *RootHandler {
	builder := newPingControllerBuilder(rootHandler)
	rootHandler.router.HandleRoute("GET", "/ping", controller.Ping(builder.Ping))
	return rootHandler
}