// Code generated by apigen DO NOT EDIT.

package models

import (
	"time"
)

// Unused imports workaround.
var _ = time.Time{}

type Error struct { 
	Code *interface{} `json:"code"`
	Message string `json:"message,omitempty"`
}
