name: Release

on:
  pull_request:
    # types: [closed]
    types: [labeled]
    branches:
      - main

jobs:
  deploy-go-apigen-server:
    permissions:
      packages: write
      contents: read

    name: Create Release
    # if: |
    #   github.event.pull_request.merged == true && 
    #   startsWith(github.event.pull_request.head.ref, 'release/') &&
    #   !contains(github.event.pull_request.labels.*.name, 'no-build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run deploy
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
