name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-go-apigen-server:
    permissions:
      contents: write

    name: Create Release
    if: |
      github.event.pull_request.merged == true && 
      (startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix/')) &&
      !contains(github.event.pull_request.labels.*.name, 'no-build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run deploy
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
