name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-go-apigen-server:
    permissions:
      packages: write
      contents: read

    name: Deploy Go APIGen Server
    if: |
      github.event.pull_request.merged == true && 
      startsWith(github.event.pull_request.head.ref, 'release/') &&
      !contains(github.event.pull_request.labels.*.name, 'no-build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run deploy
        run: make deploy/generators/go-apigen-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
