name: Test

on: 
  pull_request:
    types: [opened, synchronize, reopened]

    branches:
      - 'main'

jobs:
  build-and-test:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-build') }}
    name: Lint And Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.work'
        cache-dependency-path: 'go.work.sum'

    - run: make lint
    - run: |
        make tests
        ls -l -a .cover

    - name: Store Test Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts-pr-${{ github.event.pull_request.node_id }}
        include-hidden-files: true
        path: .cover/
        retention-days: 10
        overwrite: true