// Code generated by apigen DO NOT EDIT.

package 

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// GetPetByIDParams - Parameters for the getPetById operation.
type GetPetByIDParams struct { 
	PetID int64 `json:"petId"`
}
