// Code generated by apigen DO NOT EDIT.

package 

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type PetsResponse struct { 
	Data []*Pet `json:"data"`
}
